<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..Shared\Contracts\EndlessParties.Shared.Contracts.Events\EndlessParties.Shared.Contracts.Events.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Exceptions\EndlessParties.Shared.Exceptions\EndlessParties.Shared.Exceptions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Utils\EndlessParties.Shared.Utils.WebApiExtensions\EndlessParties.Shared.Utils.WebApiExtensions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Utils\UserContext\EndlessParties.Shared.Utils.HttpUserContext\EndlessParties.Shared.Utils.HttpUserContext.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Validations\EndlessParties.Shared.Validations\EndlessParties.Shared.Validations.csproj" />
		<ProjectReference Include="..\EndlessParties.Bookings.Api.App\EndlessParties.Bookings.Api.App.csproj" />
		<ProjectReference Include="..\EndlessParties.Bookings.Api.Infrastructure\EndlessParties.Bookings.Api.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Serilog" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="PresentationSettings.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="PresentationSettingsValidator.cs">
			<DependentUpon>PresentationSettings.cs</DependentUpon>
		</Compile>
		<Compile Update="WebApplicationBuilderExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="WebApplicationExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>