<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..Shared\Exceptions\EndlessParties.Shared.Exceptions\EndlessParties.Shared.Exceptions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Utils\EndlessParties.Shared.Utils.WebApiExtensions\EndlessParties.Shared.Utils.WebApiExtensions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Validations\EndlessParties.Shared.Validations\EndlessParties.Shared.Validations.csproj" />
		<ProjectReference Include="..\..\.Shared\Database\EndlessParties.Identity.Database\EndlessParties.Identity.Database.csproj" />
		<ProjectReference Include="..\EndlessParties.Identity.Api.App\EndlessParties.Identity.Api.App.csproj" />
		<ProjectReference Include="..\EndlessParties.Identity.Api.Infrastructure\EndlessParties.Identity.Api.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="WebApplicationBuilderExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="WebApplicationExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>