// <auto-generated />
using System;
using EndlessParties.Events.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace EndlessParties.Events.Database.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    partial class EventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EndlessParties.Events.Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasColumnName("available_seats");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.Property<NpgsqlTsVector>("description_search_vector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("description_search_vector")
                        .HasComputedColumnSql("to_tsvector('russian', coalesce(description, ''))", true);

                    b.Property<NpgsqlTsVector>("title_search_vector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("title_search_vector")
                        .HasComputedColumnSql("to_tsvector('russian', coalesce(title, ''))", true);

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("EndAt")
                        .HasDatabaseName("ix_events_end_at");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_events_start_at");

                    b.HasIndex("description_search_vector")
                        .HasDatabaseName("ix_events_description_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("description_search_vector"), "GIN");

                    b.HasIndex("title_search_vector")
                        .HasDatabaseName("ix_events_title_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("title_search_vector"), "GIN");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_dates", "end_at >= start_at");

                            t.HasCheckConstraint("ck_events_seats", "available_seats >= 0 AND total_seats >= 0 AND available_seats <= total_seats");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
