<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Application\EndlessParties.Application\EndlessParties.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Moq.AutoMock" />
		<PackageReference Include="xunit.v3.mtp-v2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
	</ItemGroup>

</Project>