<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\..Shared\Exceptions\EndlessParties.Shared.Exceptions.Models\EndlessParties.Shared.Exceptions.Models.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Errors\UsersErrors.cs">
			<DependentUpon>ApplicationErrors.cs</DependentUpon>
		</Compile>
		<Compile Update="Errors\UserPasswordErrors.cs">
			<DependentUpon>ApplicationErrors.cs</DependentUpon>
		</Compile>
		<Compile Update="Models\UserPassword.cs">
			<DependentUpon>User.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>