<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..Shared\Exceptions\EndlessParties.Shared.Exceptions\EndlessParties.Shared.Exceptions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Utils\EndlessParties.Shared.Utils.Logger\EndlessParties.Shared.Utils.Logger.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Validations\EndlessParties.Shared.Validations\EndlessParties.Shared.Validations.csproj" />
		<ProjectReference Include="..\..\.Shared\Database\EndlessParties.Events.Database\EndlessParties.Events.Database.csproj" />
		<ProjectReference Include="..\EndlessParties.Events.Api.App\EndlessParties.Events.Api.App.csproj" />
		<ProjectReference Include="..\EndlessParties.Events.Api.Infrastructure\EndlessParties.Events.Api.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="WebApplicationBuilderExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="WebApplicationExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="ClaimsPrincipalExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="PresentationSettings.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="PresentationSettingsValidator.cs">
			<DependentUpon>PresentationSettings.cs</DependentUpon>
		</Compile>
		<Compile Update="IdentitySettings.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="IdentitySettingsValidator.cs">
			<DependentUpon>IdentitySettings.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>