<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..Shared\Exceptions\EndlessParties.Shared.Exceptions\EndlessParties.Shared.Exceptions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Validations\EndlessParties.Shared.Validations\EndlessParties.Shared.Validations.csproj" />
		<ProjectReference Include="..\..\.Shared\Database\EndlessParties.Events.Database\EndlessParties.Events.Database.csproj" />
		<ProjectReference Include="..\EndlessParties.Events.Api.App\EndlessParties.Events.Api.App.csproj" />
		<ProjectReference Include="..\EndlessParties.Events.Api.Infrastructure\EndlessParties.Events.Api.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Settings.Configuration" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="LogExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="WebApplicationBuilderExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="WebApplicationExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>