<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..Shared\Utils\EndlessParties.Shared.Utils.IntegrationTests\EndlessParties.Shared.Utils.IntegrationTests.csproj" />
		<ProjectReference Include="..\..\..\Infrastructure\Database\EndlessParties.Database\EndlessParties.Database.csproj" />
		<ProjectReference Include="..\..\..\Infrastructure\EndlessParties.Infrastructure\EndlessParties.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="xunit.v3.mtp-v2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Repositories\EventFilterTestCase.cs">
			<DependentUpon>EventRepositoryTests.cs</DependentUpon>
		</Compile>
		<Compile Update="Repositories\EventFilterTestData.cs">
			<DependentUpon>EventRepositoryTests.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
