<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\..Shared\Exceptions\EndlessParties.Shared.Exceptions.Models\EndlessParties.Shared.Exceptions.Models.csproj" />
		<ProjectReference Include="..\..\..Shared\MessageBus\EndlessParties.Shared.ChannelMessageBus\EndlessParties.Shared.ChannelMessageBus.csproj" />
		<ProjectReference Include="..\..\..Shared\MessageBus\EndlessParties.Shared.MessageBus.Abstractions\EndlessParties.Shared.MessageBus.Abstractions.csproj" />
		<ProjectReference Include="..\..\..Shared\Utils\EndlessParties.Shared.Utils\EndlessParties.Shared.Utils.Exceptions.csproj" />
		<ProjectReference Include="..\..\Infrastructure\EndlessParties.Infrastructure.Abstractions\EndlessParties.Infrastructure.Abstractions.csproj" />
		<ProjectReference Include="..\EndlessParties.Application.Abstractions\EndlessParties.Application.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Riok.Mapperly" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Bookings\Services\BookingProcessorService.Logging.cs">
			<DependentUpon>BookingProcessorService.cs</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="EndlessParties.Tests.Application" />
	</ItemGroup>

</Project>