<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..Shared\Contracts\EndlessParties.Shared.Contracts.Events\EndlessParties.Shared.Contracts.Events.csproj" />
		<ProjectReference Include="..\..\..\..Shared\EventBus\EndlessParties.Shared.EventBus.Abstractions\EndlessParties.Shared.EventBus.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Exceptions\EndlessParties.Shared.Exceptions.Extensions\EndlessParties.Shared.Exceptions.Extensions.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Utils\Database\EndlessParties.Shared.Utils.Database\EndlessParties.Shared.Utils.Database.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Utils\EndlessParties.Shared.Utils.DateTime\EndlessParties.Shared.Utils.DateTime.csproj" />
		<ProjectReference Include="..\..\..\..Shared\Utils\UserContext\EndlessParties.Shared.Utils.UserContext.Abstractions\EndlessParties.Shared.Utils.UserContext.Abstractions.csproj" />
		<ProjectReference Include="..\..\.Shared\Repositories\EndlessParties.Events.Repositories.Abstractions\EndlessParties.Events.Repositories.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Mediator.SourceGenerator" />
		<PackageReference Include="Riok.Mapperly" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Features\GetAll\GetAllEventsQuery.cs">
			<DependentUpon>GetAllEventsHandler.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\GetAll\EventSearchFilterValidator.cs">
			<DependentUpon>EventSearchFilter.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\GetAll\EventPaginatedResponseMapper.cs">
			<DependentUpon>EventPaginatedResponse.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\GetAll\EventSearchFilterMapper.cs">
			<DependentUpon>EventSearchFilter.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\Create\CreateEventCommand.cs">
			<DependentUpon>CreateEventHandler.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\Create\CreateEventRequestValidator.cs">
			<DependentUpon>CreateEventRequest.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\GetById\GetEventByIdQuery.cs">
			<DependentUpon>GetEventByIdHandler.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\Update\UpdateEventCommand.cs">
			<DependentUpon>UpdateEventHandler.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\Update\UpdateEventRequestValidator.cs">
			<DependentUpon>UpdateEventRequest.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\Remove\DeleteEventCommand.cs">
			<DependentUpon>DeleteEventHandler.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\ReserveSeats\ReserveEventSeatsCommand.cs">
			<DependentUpon>ReserveEventSeatsHandler.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\ReserveSeats\ReserveEventSeatsHandler.Logging.cs">
			<DependentUpon>ReserveEventSeatsHandler.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\ReleaseSeats\ReleaseEventSeatsCommand.cs">
			<DependentUpon>ReleaseEventSeatsHandler.cs</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Include="**/.*/**/*.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Features\.Shared\EventDataValidator.cs">
			<DependentUpon>EventData.cs</DependentUpon>
		</Compile>
		<Compile Update="Features\.Shared\EventMapper.cs">
			<DependentUpon>EventResponse.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>