<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..Shared\Utils\EndlessParties.Shared.Utils.Logger\EndlessParties.Shared.Utils.Logger.csproj" />
		<ProjectReference Include="..\EndlessParties.Events.Worker.App\EndlessParties.Events.Worker.App.csproj" />
		<ProjectReference Include="..\EndlessParties.Events.Worker.Infrastructure\EndlessParties.Events.Worker.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="WebApplicationBuilderExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
		<Compile Update="WebApplicationExtensions.cs">
			<DependentUpon>ServiceCollectionExtensions.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>